version: "3.7"
services:
    chrome:
        image: selenium/standalone-chrome
        container_name: chrome
        ports:
            - 4444:4444
            - 7900:7900
        environment:
          - SE_NODE_MAX_SESSIONS=2
        restart: always
        volumes:
            - /dev/shm:/dev/shm
        
    mongo:
        image: mongo:4.4.9
        container_name: mongodb
        restart: always
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD
            - MONGO_INITDB_DATABASE
        volumes:
            - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
            - ./technologies_list.json:/preload/technologies_list.json
            - ./questions.json:/preload/questions.json
            - ./data:/data/db    

    backend:
        build: .
        restart: always
        links:
            - mongo
            - chrome
        volumes:
            - ./cron_log.txt:/cron_log.txt
            # - ./env/lib/python3.10/site-packages:/usr/local/lib/python3.10/dist-packages:ro
        depends_on: 
            - mongo
            - chrome

    nginx:
        image: nginx
        restart: always
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./covidsite/static:/static
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./server.crt:/certs/server.crt:ro
            - ./server.key:/certs/server.key:ro
        links:
            - backend
        depends_on:
            - backend