version: "3.7"
services:
    mongo:
        image: mongo
        container_name: mongodb
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD
            - MONGO_INITDB_DATABASE
        volumes:
            - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
            - ./technologies_list.json:/preload/technologies_list.json
            - ./questions.json:/preload/questions.json
            - ./data:/data/db    

    backend:
        build: .
        container_name: backend
        restart: always
        links:
            - mongo

    nginx:
        image: nginx
        container_name: nginx
        restart: always
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./covidsite/static:/static
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./server.crt:/certs/server.crt:ro
            - ./server.key:/certs/server.key:ro
        links:
            - backend

